name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Add private GitHub registry to NuGet
      run: dotnet nuget add source https://nuget.pkg.github.com/compiledio/index.json --name "nuget" --username nuget --password 45a74283c1ec66bd76af621671ef23145b7a43a0 --store-password-in-clear-text
    - name: Install dependencies
      run: dotnet restore /home/runner/work/Quiplogs_API/Quiplogs_API/Api/Api.sln
    - name: Build
      run: dotnet build /home/runner/work/Quiplogs_API/Quiplogs_API/Api/Api.sln --configuration Release --no-restore
    - name: Test
      run: dotnet test /home/runner/work/Quiplogs_API/Quiplogs_API/Api/Api.sln --no-restore --verbosity normal
